---
- name: Disable Objects
  ansible.builtin.uri:
    url: "https://{{ role_nutanix_prism_api_url_base }}/api/nutanix/v3/services/nucalm"
    method: POST
    body:
      state: DISABLE
      enable_nutanix_apps: "{{ nutanix_calm_enable_default_apps }}"
    validate_certs: "{{ role_nutanix_pc_svc_objects_validate_certs }}"
    body_format: json
    status_code: 202
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
  register: role_nutanix_pc_svc_objects_disable_task

- name: Debug role_nutanix_pc_svc_objects_disable_task
  ansible.builtin.debug:
    var: role_nutanix_pc_svc_objects_disable_task
  when:
    - role_nutanix_pc_svc_objects_debug

- name: Wait for Objects disable task to complete
  ansible.builtin.import_role:
    name: grdavies.role_nutanix_prism_monitor_task
  vars:
    role_nutanix_prism_monitor_task_host: "{{ role_nutanix_pc_svc_objects_host }}"
    role_nutanix_prism_monitor_task_username: "{{ role_nutanix_pc_svc_objects_username }}"
    role_nutanix_prism_monitor_task_password: "{{ role_nutanix_pc_svc_objects_password }}"
    role_nutanix_prism_monitor_task_port: "{{ role_nutanix_pc_svc_objects_port | default(omit) }}"
    role_nutanix_prism_monitor_task_validate_certs: "{{ role_nutanix_pc_svc_objects_validate_certs | default(omit) }}"
    role_nutanix_prism_monitor_task_debug: "{{ role_nutanix_pc_svc_objects_debug | default(omit) }}"
    role_nutanix_prism_monitor_task_uuid: "{{ role_nutanix_pc_svc_objects_disable_task.json.task_uuid }}"
    role_nutanix_prism_monitor_task_retries: 60
    role_nutanix_prism_monitor_task_retry_delay: 15
