---
# tasks file for role_nutanix_pc_svc_objects
- name: Setup connection to Nutanix API
  ansible.builtin.include_role:
    name: grdavies.role_nutanix_prism_api
  vars:
    role_nutanix_prism_api_host: "{{ role_nutanix_pc_svc_objects_host }}"
    role_nutanix_prism_api_host_username: "{{ role_nutanix_pc_svc_objects_host_username }}"
    role_nutanix_prism_api_host_password: "{{ role_nutanix_pc_svc_objects_host_password }}"
    role_nutanix_prism_api_host_port: "{{ role_nutanix_pc_svc_objects_host_port | default(omit) }}"
    role_nutanix_prism_api_host_validate_certs: "{{ role_nutanix_pc_svc_objects_host_validate_certs | default(omit) }}"
    role_nutanix_prism_api_debug: "{{ role_nutanix_pc_svc_objects_debug | default(omit) }}"

- name: "Task can only be run against Prism Central"
  ansible.builtin.fail:
    msg: "'role_nutanix_pc_svc_objects_host' needs to be set to the IP or VIP of Prism Central. Please check the variable and try again."
  when:
    - role_nutanix_prism_api_endpoint_type != 'pc'

- name: Get Objects state
  ansible.builtin.include_tasks: get_state.yml

- name: Enable Objects
  ansible.builtin.include_tasks: enable_feature.yml
  when:
    - role_nutanix_pc_svc_objects_state.json.service_enablement_status | lower != "enabled"
    - role_nutanix_pc_svc_objects_enable | default(false)

- name: Disable Objects
  ansible.builtin.include_tasks: disable_feature.yml
  when:
    - role_nutanix_pc_svc_objects_state.json.service_enablement_status| lower == "enabled"
    - role_nutanix_pc_svc_objects_enable | default(true)
